image:
  repository: ghcr.io/alexj9837/learn-deploy
  # tag defaults to Chart.yaml appVersion if not set
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: nginx
  host: "ret43730.diamond.ac.uk"
  # e.g. first-step.ret43730.pollux.diamond.ac.uk
  annotations: {}
  #   nginx.ingress.kubernetes.io/rewrite-target: /
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

securityContext:
  runAsNonRoot: true
  runAsUser: 1000

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
# -- Liveness probe, if configured kubernetes will kill the pod and start a new one if failed consecutively.
# This is automatically disabled when in debug mode.
livenessProbe:
  httpGet:
    path: /healthz
    port: http
  failureThreshold: 3
  periodSeconds: 10

# -- Readiness probe, if configured kubernetes will not route traffic to this pod if failed consecutively.
# This could allow the service time to recover if it is being overwhelmed by traffic, but without the
# to ability to load balance or scale up/outwards, upstream services will need to know to back off.
# This is automatically disabled when in debug mode.
readinessProbe:
  httpGet:
    path: /healthz
    port: http
  failureThreshold: 2
  periodSeconds: 10

# -- A more lenient livenessProbe to allow the service to start fully.
# This is automatically disabled when in debug mode.
startupProbe:
  httpGet:
    path: /healthz
    port: http
  failureThreshold: 5
  periodSeconds: 10
