image:
  repository: ghcr.io/alexj9837/l-deploy
  # tag defaults to Chart.yaml appVersion if not set
  tag: ""
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: false
  # className: nginx
  host: ""
  # e.g. first-step.ret43730.pollux.diamond.ac.uk
  annotations: {}
  #   nginx.ingress.kubernetes.io/rewrite-target: /

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  path: /healthz
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  path: /healthz
  initialDelaySeconds: 5
  periodSeconds: 10
